### ISSUE TITLE
Doesn't work with ES6 consts

### ISSUE THREAD

**Issue by erbridge** [jhnns/rewire#79] opened 2015-10-14 15:15 UTC
You get errors like this:

```
TypeError: Assignment to constant variable.
  at eval (eval at __set__ (my-module.js:73:19), <anonymous>:1:21)
  at Object.__set__ (my-module.js:73:5)
  at Context.<anonymous> (my-module-test.js:131:55)
```

**Comment by brenolf** [comment] 2015-10-15 17:39
:+1: for this. My workaround was using `let` instead of `const` to enable it to rewire.

**Comment by erbridge** [comment] 2015-10-15 20:32
Yes, that works, and is my current workaround, but I really don't want to have to open the code up to bugs in order to test it...

**Comment by jhnns** [comment] 2015-11-02 01:15
Well ... re-assigning `const` is not possible, rewire can't change this.

In order to do this, rewire would need to change the code (like @brenolf did manually). Therefore, we would need to use a parser which is currently out of scope.

However, if we want to support ES6 modules someday, we will need a parser anyway, so I'll consider this when rewriting rewire.

**Comment by dcrockwell** [comment] 2015-11-08 01:55
+1 for ES6 consts. Thanks to @brenolf for the workaround.

**Comment by alexweber** [comment] 2016-01-28 10:48
@erbridge @brenolf dcrockwell @dcrockwell For what it's worth, [proxyquire](https://github.com/thlorenz/proxyquire) _seems_ to work fine using ES6 consts.  

I've yet to write some more complex tests with it but initial results are encouraging.

**Comment by kaktus42** [comment] 2016-05-18 21:39
I can't reproduce this issue.
I can rewire const functions.

**Comment by jhnns** [comment] 2016-05-19 07:34
Do you have an example? I'm pretty sure that this can not work.

**Comment by kaktus42** [comment] 2016-05-19 09:25
```js
var r = rewire('./reducer');
const reduceAddAction = r.__get__('reduceAddAction');
```

Where `reduceAddAction` is a const function.

But maybe you were talking about overwriting?

**Comment by jhnns** [comment] 2016-05-19 11:42
> But maybe you were talking about overwriting?

Exactly

**Comment by awinder** [comment] 2016-06-09 13:02
Riffing on what @kaktus42 was saying though, you can take advantage of the way JS const works for evil and profit in the case when it's an object: 

```
var r = rewire('./reducer');
const reduceAddAction = r.__get__('reduceAddAction');
reduceAddAction.method.to.stub = sinon.stub();
```

In this case you're not reassigning the variable identifier, and you're changing a referenced value, so it is possible, whether or not it's a good idea or not is another thing entirely 😄

**Comment by jhnns** [comment] 2016-06-10 07:41
I think it's totally valid to change `const` objects, because `const` does not mean that the object itself is frozen (you could use `Object.freeze()` for that 😉 ). However, I would not change the code just for the test framework.

**Comment by daithi-coombes** [comment] 2016-06-29 16:50
+1 for allowing rewire of const's

**Comment by kimpellikaan** [comment] 2016-08-20 13:12
+1 again!

**Comment by rewiregps** [comment] 2016-08-20 15:17
you should check this out : https://mathiasbynens.be/notes/es6-const
+1 for [https://www.rewiresecurity.co.uk](rewire)

**Comment by ScionOfBytes** [comment] 2016-09-14 11:52
+1 yet again!

**Comment by ioanlucut** [comment] 2016-09-15 13:46
+1

**Comment by shivarajnaidu** [comment] 2016-09-29 05:34
+1 for const and full es6 support...

**Comment by tbranyen** [comment] 2016-10-15 20:54
@rewiregps You link an article that very well articulates why this cannot work. The bindings are immutable. So this already works exactly how it should. You cannot override a const binding, which is what rewire does.

**Comment by jhnns** [comment] 2016-10-20 16:23
@shivarajnaidu I'm thinking about ES6 support, but it's not that easy :) – especially as long as the loader spec is not finished yet.

**Comment by jsrraman** [comment] 2016-11-24 02:45
Well, in my case, I needed to stub a method from a private const from a module which in turn required a module.  [proxyquire](https://github.com/thlorenz/proxyquire) supports this use case

For example

```
my-module.js
const thirdPartyModule = require('..')

// Original function
thirdPartyModule.getName()

test-my-module-spec.js
const proxyquire = require('proxyquire');
const socketUtil = proxyquire('./my-module', { 'thirdPartyModule': thirdPartyModuleStub });

thirdPartyModuleStub.getName = () => {
      return 'stubbedName;
    };

```

**Comment by jhnns** [comment] 2018-04-09 23:26
Rewiring `const` is supported since `3.0.0`

**Closed by jhnns** 2018-04-09 23:26 UTC

**Comment by goyney** [comment] 2018-04-23 01:57
@jhnns 4.0.0 here, this does not work.

**main.js**
`const { apiRoot, defaultPort } = require('config');`

**main.test.js**
```
const myModule = rewire('myModule');

myModule.__set__('defaultPort', 123);
```

> TypeError: Assignment to constant variable.

**Comment by jhnns** [comment] 2018-04-24 11:37
@goyney Your example should work. Could you provide a demo that makes it reproducible. I did found a bug though where `const` was not properly detected when it was written like: `const{ apiRoot ...`. I published a fix with [`4.0.1`](https://github.com/jhnns/rewire/releases/tag/v4.0.1)

**Comment by Sufiane** [comment] 2018-07-30 09:02
@jhnns I do have the same problem as @goyney :( 
I already have `rewire 4.0.1`

The only difference I have is that it's not from destructuring.

Demo:
index.js:
```
const myPromisifiedFunction = promisify(someFunct.ToPromisify)
```
index.test.js:
```
const myModule = rewire('../myModule')
const myStub = sinon.stub()
const myStubbedFunction = myModule.__set__('myPromisifiedFunction', myStub)
```

And what I get when running tests is:
`TypeError: Assignment to constant variable.
      at eval (eval at __set__ (index.js:159:5), <anonymous>:1:19)
      at Object.__set__ (index.js:159:5)
      at Object.<anonymous> (test/index.test.js:14:48)`

**Comment by pandomic** [comment] 2018-10-22 21:02
As a possible "dirty" workaround, it's possible to `__get__` the function you need to test (which you expect to call other funcs), convert it to string, eval and test it in the context of your test. It works for small functions, but I'm sure with larger ones it might be a bit painful.

```
// myfunc.js

const unmockable = (a) => `Hello ${a}`;
const myLovelyFunc = (a) => unmockable(a);

module.exports = { myLovelyFunc };

// - - - - - - - - - - - - - - - somewhere in myfunc.test.js - - - - - - - - - - - - - - -

const myLovelyFunc = rewire('./myfunc.js').__get__('myLovelyFunc');
const subject = eval(myLovelyFunc.toString());

// Redefining function's local context
const unmockable - jest.fn(`Bye, ${a}`);

subject('Dude'); //=> Bye, Dude

expect(unmockable).toHaveBeenCalledWith('Dude');
```

**Comment by andreisaikouski** [comment] 2021-11-25 18:46
Still having this issue even with `rewire 5.0.0`, any fixes or workarounds?

**Comment by siva-natarajan** [comment] 2022-01-11 21:33
Still having this issue even with rewire 6.0.0, any fixes or workarounds?

**Comment by ahmedfourati** [comment] 2022-04-08 15:53
I just had to change es6 to es5 and it worked.
